export async function registerAllElements() {
  const {
    HTMLNSAccessibilityCustomActionElement,
    HTMLNSAccessibilityCustomRotorElement,
    HTMLNSAccessibilityCustomRotorItemResultElement,
    HTMLNSAccessibilityCustomRotorSearchParametersElement,
    HTMLNSAccessibilityElementElement,
    HTMLNSActionCellElement,
    HTMLNSAlertElement,
    HTMLNSAlignmentFeedbackFilterElement,
    HTMLNSAnimationElement,
    HTMLNSAnimationContextElement,
    HTMLNSAppearanceElement,
    HTMLNSApplicationElement,
    HTMLNSArrayControllerElement,
    HTMLNSATSTypesetterElement,
    HTMLNSBezierPathElement,
    HTMLNSBindingSelectionMarkerElement,
    HTMLNSBitmapImageRepElement,
    HTMLNSBoxElement,
    HTMLNSBrowserElement,
    HTMLNSBrowserCellElement,
    HTMLNSButtonElement,
    HTMLNSButtonCellElement,
    HTMLNSButtonTouchBarItemElement,
    HTMLNSCachedImageRepElement,
    HTMLNSCandidateListTouchBarItemElement,
    HTMLNSCellElement,
    HTMLNSCIImageRepElement,
    HTMLNSClickGestureRecognizerElement,
    HTMLNSClipViewElement,
    HTMLNSCollectionLayoutAnchorElement,
    HTMLNSCollectionLayoutBoundarySupplementaryItemElement,
    HTMLNSCollectionLayoutDecorationItemElement,
    HTMLNSCollectionLayoutDimensionElement,
    HTMLNSCollectionLayoutEdgeSpacingElement,
    HTMLNSCollectionLayoutGroupElement,
    HTMLNSCollectionLayoutGroupCustomItemElement,
    HTMLNSCollectionLayoutItemElement,
    HTMLNSCollectionLayoutSectionElement,
    HTMLNSCollectionLayoutSizeElement,
    HTMLNSCollectionLayoutSpacingElement,
    HTMLNSCollectionLayoutSupplementaryItemElement,
    HTMLNSCollectionViewElement,
    HTMLNSCollectionViewCompositionalLayoutElement,
    HTMLNSCollectionViewCompositionalLayoutConfigurationElement,
    HTMLNSCollectionViewDiffableDataSourceElement,
    HTMLNSCollectionViewFlowLayoutElement,
    HTMLNSCollectionViewFlowLayoutInvalidationContextElement,
    HTMLNSCollectionViewGridLayoutElement,
    HTMLNSCollectionViewItemElement,
    HTMLNSCollectionViewLayoutElement,
    HTMLNSCollectionViewLayoutAttributesElement,
    HTMLNSCollectionViewLayoutInvalidationContextElement,
    HTMLNSCollectionViewTransitionLayoutElement,
    HTMLNSCollectionViewUpdateItemElement,
    HTMLNSColorElement,
    HTMLNSColorListElement,
    HTMLNSColorPanelElement,
    HTMLNSColorPickerElement,
    HTMLNSColorPickerTouchBarItemElement,
    HTMLNSColorSamplerElement,
    HTMLNSColorSpaceElement,
    HTMLNSColorWellElement,
    HTMLNSComboBoxElement,
    HTMLNSComboBoxCellElement,
    HTMLNSComboButtonElement,
    HTMLNSControlElement,
    HTMLNSControllerElement,
    HTMLNSCursorElement,
    HTMLNSCustomImageRepElement,
    HTMLNSCustomTouchBarItemElement,
    HTMLNSDataAssetElement,
    HTMLNSDatePickerElement,
    HTMLNSDatePickerCellElement,
    HTMLNSDictionaryControllerElement,
    HTMLNSDictionaryControllerKeyValuePairElement,
    HTMLNSDiffableDataSourceSnapshotElement,
    HTMLNSDockTileElement,
    HTMLNSDocumentElement,
    HTMLNSDocumentControllerElement,
    HTMLNSDraggingImageComponentElement,
    HTMLNSDraggingItemElement,
    HTMLNSDraggingSessionElement,
    HTMLNSDrawerElement,
    HTMLNSEPSImageRepElement,
    HTMLNSEventElement,
    HTMLNSFilePromiseProviderElement,
    HTMLNSFilePromiseReceiverElement,
    HTMLNSFontElement,
    HTMLNSFontAssetRequestElement,
    HTMLNSFontCollectionElement,
    HTMLNSFontDescriptorElement,
    HTMLNSFontManagerElement,
    HTMLNSFontPanelElement,
    HTMLNSFormElement,
    HTMLNSFormCellElement,
    HTMLNSGestureRecognizerElement,
    HTMLNSGlyphGeneratorElement,
    HTMLNSGlyphInfoElement,
    HTMLNSGradientElement,
    HTMLNSGraphicsContextElement,
    HTMLNSGridCellElement,
    HTMLNSGridColumnElement,
    HTMLNSGridRowElement,
    HTMLNSGridViewElement,
    HTMLNSGroupTouchBarItemElement,
    HTMLNSHapticFeedbackManagerElement,
    HTMLNSHelpManagerElement,
    HTMLNSImageElement,
    HTMLNSImageCellElement,
    HTMLNSImageRepElement,
    HTMLNSImageSymbolConfigurationElement,
    HTMLNSImageViewElement,
    HTMLNSInputManagerElement,
    HTMLNSInputServerElement,
    HTMLNSLayoutAnchorElement,
    HTMLNSLayoutConstraintElement,
    HTMLNSLayoutDimensionElement,
    HTMLNSLayoutGuideElement,
    HTMLNSLayoutManagerElement,
    HTMLNSLayoutXAxisAnchorElement,
    HTMLNSLayoutYAxisAnchorElement,
    HTMLNSLevelIndicatorElement,
    HTMLNSLevelIndicatorCellElement,
    HTMLNSMagnificationGestureRecognizerElement,
    HTMLNSMatrixElement,
    HTMLNSMediaLibraryBrowserControllerElement,
    HTMLNSMenuElement,
    HTMLNSMenuItemElement,
    HTMLNSMenuItemBadgeElement,
    HTMLNSMenuItemCellElement,
    HTMLNSMenuToolbarItemElement,
    HTMLNSMovieElement,
    HTMLNSMutableFontCollectionElement,
    HTMLNSMutableParagraphStyleElement,
    HTMLNSNibElement,
    HTMLNSObjectElement,
    HTMLNSObjectControllerElement,
    HTMLNSOpenGLContextElement,
    HTMLNSOpenGLPixelBufferElement,
    HTMLNSOpenGLPixelFormatElement,
    HTMLNSOpenGLViewElement,
    HTMLNSOpenPanelElement,
    HTMLNSOutlineViewElement,
    HTMLNSPageControllerElement,
    HTMLNSPageLayoutElement,
    HTMLNSPanelElement,
    HTMLNSPanGestureRecognizerElement,
    HTMLNSParagraphStyleElement,
    HTMLNSPasteboardElement,
    HTMLNSPasteboardItemElement,
    HTMLNSPathCellElement,
    HTMLNSPathComponentCellElement,
    HTMLNSPathControlElement,
    HTMLNSPathControlItemElement,
    HTMLNSPDFImageRepElement,
    HTMLNSPDFInfoElement,
    HTMLNSPDFPanelElement,
    HTMLNSPersistentDocumentElement,
    HTMLNSPickerTouchBarItemElement,
    HTMLNSPICTImageRepElement,
    HTMLNSPopoverElement,
    HTMLNSPopoverTouchBarItemElement,
    HTMLNSPopUpButtonElement,
    HTMLNSPopUpButtonCellElement,
    HTMLNSPredicateEditorElement,
    HTMLNSPredicateEditorRowTemplateElement,
    HTMLNSPressGestureRecognizerElement,
    HTMLNSPressureConfigurationElement,
    HTMLNSPreviewRepresentingActivityItemElement,
    HTMLNSPrinterElement,
    HTMLNSPrintInfoElement,
    HTMLNSPrintOperationElement,
    HTMLNSPrintPanelElement,
    HTMLNSProgressIndicatorElement,
    HTMLNSResponderElement,
    HTMLNSRotationGestureRecognizerElement,
    HTMLNSRuleEditorElement,
    HTMLNSRulerMarkerElement,
    HTMLNSRulerViewElement,
    HTMLNSRunningApplicationElement,
    HTMLNSSavePanelElement,
    HTMLNSScreenElement,
    HTMLNSScrollerElement,
    HTMLNSScrollViewElement,
    HTMLNSScrubberElement,
    HTMLNSScrubberArrangedViewElement,
    HTMLNSScrubberFlowLayoutElement,
    HTMLNSScrubberImageItemViewElement,
    HTMLNSScrubberItemViewElement,
    HTMLNSScrubberLayoutElement,
    HTMLNSScrubberLayoutAttributesElement,
    HTMLNSScrubberProportionalLayoutElement,
    HTMLNSScrubberSelectionStyleElement,
    HTMLNSScrubberSelectionViewElement,
    HTMLNSScrubberTextItemViewElement,
    HTMLNSSearchFieldElement,
    HTMLNSSearchFieldCellElement,
    HTMLNSSearchToolbarItemElement,
    HTMLNSSecureTextFieldElement,
    HTMLNSSecureTextFieldCellElement,
    HTMLNSSegmentedCellElement,
    HTMLNSSegmentedControlElement,
    HTMLNSShadowElement,
    HTMLNSSharingServiceElement,
    HTMLNSSharingServicePickerElement,
    HTMLNSSharingServicePickerToolbarItemElement,
    HTMLNSSharingServicePickerTouchBarItemElement,
    HTMLNSSliderElement,
    HTMLNSSliderAccessoryElement,
    HTMLNSSliderAccessoryBehaviorElement,
    HTMLNSSliderCellElement,
    HTMLNSSliderTouchBarItemElement,
    HTMLNSSoundElement,
    HTMLNSSpeechRecognizerElement,
    HTMLNSSpeechSynthesizerElement,
    HTMLNSSpellCheckerElement,
    HTMLNSSplitViewElement,
    HTMLNSSplitViewControllerElement,
    HTMLNSSplitViewItemElement,
    HTMLNSStackViewElement,
    HTMLNSStatusBarElement,
    HTMLNSStatusBarButtonElement,
    HTMLNSStatusItemElement,
    HTMLNSStepperElement,
    HTMLNSStepperCellElement,
    HTMLNSStepperTouchBarItemElement,
    HTMLNSStoryboardElement,
    HTMLNSStoryboardSegueElement,
    HTMLNSStringDrawingContextElement,
    HTMLNSSwitchElement,
    HTMLNSTableCellViewElement,
    HTMLNSTableColumnElement,
    HTMLNSTableHeaderCellElement,
    HTMLNSTableHeaderViewElement,
    HTMLNSTableRowViewElement,
    HTMLNSTableViewElement,
    HTMLNSTableViewDiffableDataSourceElement,
    HTMLNSTableViewRowActionElement,
    HTMLNSTabViewElement,
    HTMLNSTabViewControllerElement,
    HTMLNSTabViewItemElement,
    HTMLNSTextElement,
    HTMLNSTextAlternativesElement,
    HTMLNSTextAttachmentElement,
    HTMLNSTextAttachmentCellElement,
    HTMLNSTextAttachmentViewProviderElement,
    HTMLNSTextBlockElement,
    HTMLNSTextCheckingControllerElement,
    HTMLNSTextContainerElement,
    HTMLNSTextContentManagerElement,
    HTMLNSTextContentStorageElement,
    HTMLNSTextElementElement,
    HTMLNSTextFieldElement,
    HTMLNSTextFieldCellElement,
    HTMLNSTextFinderElement,
    HTMLNSTextInputContextElement,
    HTMLNSTextInsertionIndicatorElement,
    HTMLNSTextLayoutFragmentElement,
    HTMLNSTextLayoutManagerElement,
    HTMLNSTextLineFragmentElement,
    HTMLNSTextListElement,
    HTMLNSTextListElementElement,
    HTMLNSTextParagraphElement,
    HTMLNSTextRangeElement,
    HTMLNSTextSelectionElement,
    HTMLNSTextSelectionNavigationElement,
    HTMLNSTextTabElement,
    HTMLNSTextTableElement,
    HTMLNSTextTableBlockElement,
    HTMLNSTextViewElement,
    HTMLNSTextViewportLayoutControllerElement,
    HTMLNSTintConfigurationElement,
    HTMLNSTitlebarAccessoryViewControllerElement,
    HTMLNSTokenFieldElement,
    HTMLNSTokenFieldCellElement,
    HTMLNSToolbarElement,
    HTMLNSToolbarItemElement,
    HTMLNSToolbarItemGroupElement,
    HTMLNSTouchElement,
    HTMLNSTouchBarElement,
    HTMLNSTouchBarItemElement,
    HTMLNSTrackingAreaElement,
    HTMLNSTrackingSeparatorToolbarItemElement,
    HTMLNSTreeControllerElement,
    HTMLNSTreeNodeElement,
    HTMLNSTypesetterElement,
    HTMLNSUserDefaultsControllerElement,
    HTMLNSUserInterfaceCompressionOptionsElement,
    HTMLNSViewElement,
    HTMLNSViewAnimationElement,
    HTMLNSViewControllerElement,
    HTMLNSVisualEffectViewElement,
    HTMLNSWindowElement,
    HTMLNSWindowControllerElement,
    HTMLNSWindowTabElement,
    HTMLNSWindowTabGroupElement,
    HTMLNSWorkspaceElement,
    HTMLNSWorkspaceAuthorizationElement,
    HTMLNSWorkspaceOpenConfigurationElement,
  } = await import('./generated-elements.js');

  HTMLNSAccessibilityCustomActionElement.defineCustomElement();
  HTMLNSAccessibilityCustomRotorElement.defineCustomElement();
  HTMLNSAccessibilityCustomRotorItemResultElement.defineCustomElement();
  HTMLNSAccessibilityCustomRotorSearchParametersElement.defineCustomElement();
  HTMLNSAccessibilityElementElement.defineCustomElement();
  HTMLNSActionCellElement.defineCustomElement();
  HTMLNSAlertElement.defineCustomElement();
  HTMLNSAlignmentFeedbackFilterElement.defineCustomElement();
  HTMLNSAnimationElement.defineCustomElement();
  HTMLNSAnimationContextElement.defineCustomElement();
  HTMLNSAppearanceElement.defineCustomElement();
  HTMLNSApplicationElement.defineCustomElement();
  HTMLNSArrayControllerElement.defineCustomElement();
  HTMLNSATSTypesetterElement.defineCustomElement();
  HTMLNSBezierPathElement.defineCustomElement();
  HTMLNSBindingSelectionMarkerElement.defineCustomElement();
  HTMLNSBitmapImageRepElement.defineCustomElement();
  HTMLNSBoxElement.defineCustomElement();
  HTMLNSBrowserElement.defineCustomElement();
  HTMLNSBrowserCellElement.defineCustomElement();
  HTMLNSButtonElement.defineCustomElement();
  HTMLNSButtonCellElement.defineCustomElement();
  HTMLNSButtonTouchBarItemElement.defineCustomElement();
  HTMLNSCachedImageRepElement.defineCustomElement();
  HTMLNSCandidateListTouchBarItemElement.defineCustomElement();
  HTMLNSCellElement.defineCustomElement();
  HTMLNSCIImageRepElement.defineCustomElement();
  HTMLNSClickGestureRecognizerElement.defineCustomElement();
  HTMLNSClipViewElement.defineCustomElement();
  HTMLNSCollectionLayoutAnchorElement.defineCustomElement();
  HTMLNSCollectionLayoutBoundarySupplementaryItemElement.defineCustomElement();
  HTMLNSCollectionLayoutDecorationItemElement.defineCustomElement();
  HTMLNSCollectionLayoutDimensionElement.defineCustomElement();
  HTMLNSCollectionLayoutEdgeSpacingElement.defineCustomElement();
  HTMLNSCollectionLayoutGroupElement.defineCustomElement();
  HTMLNSCollectionLayoutGroupCustomItemElement.defineCustomElement();
  HTMLNSCollectionLayoutItemElement.defineCustomElement();
  HTMLNSCollectionLayoutSectionElement.defineCustomElement();
  HTMLNSCollectionLayoutSizeElement.defineCustomElement();
  HTMLNSCollectionLayoutSpacingElement.defineCustomElement();
  HTMLNSCollectionLayoutSupplementaryItemElement.defineCustomElement();
  HTMLNSCollectionViewElement.defineCustomElement();
  HTMLNSCollectionViewCompositionalLayoutElement.defineCustomElement();
  HTMLNSCollectionViewCompositionalLayoutConfigurationElement.defineCustomElement();
  HTMLNSCollectionViewDiffableDataSourceElement.defineCustomElement();
  HTMLNSCollectionViewFlowLayoutElement.defineCustomElement();
  HTMLNSCollectionViewFlowLayoutInvalidationContextElement.defineCustomElement();
  HTMLNSCollectionViewGridLayoutElement.defineCustomElement();
  HTMLNSCollectionViewItemElement.defineCustomElement();
  HTMLNSCollectionViewLayoutElement.defineCustomElement();
  HTMLNSCollectionViewLayoutAttributesElement.defineCustomElement();
  HTMLNSCollectionViewLayoutInvalidationContextElement.defineCustomElement();
  HTMLNSCollectionViewTransitionLayoutElement.defineCustomElement();
  HTMLNSCollectionViewUpdateItemElement.defineCustomElement();
  HTMLNSColorElement.defineCustomElement();
  HTMLNSColorListElement.defineCustomElement();
  HTMLNSColorPanelElement.defineCustomElement();
  HTMLNSColorPickerElement.defineCustomElement();
  HTMLNSColorPickerTouchBarItemElement.defineCustomElement();
  HTMLNSColorSamplerElement.defineCustomElement();
  HTMLNSColorSpaceElement.defineCustomElement();
  HTMLNSColorWellElement.defineCustomElement();
  HTMLNSComboBoxElement.defineCustomElement();
  HTMLNSComboBoxCellElement.defineCustomElement();
  HTMLNSComboButtonElement.defineCustomElement();
  HTMLNSControlElement.defineCustomElement();
  HTMLNSControllerElement.defineCustomElement();
  HTMLNSCursorElement.defineCustomElement();
  HTMLNSCustomImageRepElement.defineCustomElement();
  HTMLNSCustomTouchBarItemElement.defineCustomElement();
  HTMLNSDataAssetElement.defineCustomElement();
  HTMLNSDatePickerElement.defineCustomElement();
  HTMLNSDatePickerCellElement.defineCustomElement();
  HTMLNSDictionaryControllerElement.defineCustomElement();
  HTMLNSDictionaryControllerKeyValuePairElement.defineCustomElement();
  HTMLNSDiffableDataSourceSnapshotElement.defineCustomElement();
  HTMLNSDockTileElement.defineCustomElement();
  HTMLNSDocumentElement.defineCustomElement();
  HTMLNSDocumentControllerElement.defineCustomElement();
  HTMLNSDraggingImageComponentElement.defineCustomElement();
  HTMLNSDraggingItemElement.defineCustomElement();
  HTMLNSDraggingSessionElement.defineCustomElement();
  HTMLNSDrawerElement.defineCustomElement();
  HTMLNSEPSImageRepElement.defineCustomElement();
  HTMLNSEventElement.defineCustomElement();
  HTMLNSFilePromiseProviderElement.defineCustomElement();
  HTMLNSFilePromiseReceiverElement.defineCustomElement();
  HTMLNSFontElement.defineCustomElement();
  HTMLNSFontAssetRequestElement.defineCustomElement();
  HTMLNSFontCollectionElement.defineCustomElement();
  HTMLNSFontDescriptorElement.defineCustomElement();
  HTMLNSFontManagerElement.defineCustomElement();
  HTMLNSFontPanelElement.defineCustomElement();
  HTMLNSFormElement.defineCustomElement();
  HTMLNSFormCellElement.defineCustomElement();
  HTMLNSGestureRecognizerElement.defineCustomElement();
  HTMLNSGlyphGeneratorElement.defineCustomElement();
  HTMLNSGlyphInfoElement.defineCustomElement();
  HTMLNSGradientElement.defineCustomElement();
  HTMLNSGraphicsContextElement.defineCustomElement();
  HTMLNSGridCellElement.defineCustomElement();
  HTMLNSGridColumnElement.defineCustomElement();
  HTMLNSGridRowElement.defineCustomElement();
  HTMLNSGridViewElement.defineCustomElement();
  HTMLNSGroupTouchBarItemElement.defineCustomElement();
  HTMLNSHapticFeedbackManagerElement.defineCustomElement();
  HTMLNSHelpManagerElement.defineCustomElement();
  HTMLNSImageElement.defineCustomElement();
  HTMLNSImageCellElement.defineCustomElement();
  HTMLNSImageRepElement.defineCustomElement();
  HTMLNSImageSymbolConfigurationElement.defineCustomElement();
  HTMLNSImageViewElement.defineCustomElement();
  HTMLNSInputManagerElement.defineCustomElement();
  HTMLNSInputServerElement.defineCustomElement();
  HTMLNSLayoutAnchorElement.defineCustomElement();
  HTMLNSLayoutConstraintElement.defineCustomElement();
  HTMLNSLayoutDimensionElement.defineCustomElement();
  HTMLNSLayoutGuideElement.defineCustomElement();
  HTMLNSLayoutManagerElement.defineCustomElement();
  HTMLNSLayoutXAxisAnchorElement.defineCustomElement();
  HTMLNSLayoutYAxisAnchorElement.defineCustomElement();
  HTMLNSLevelIndicatorElement.defineCustomElement();
  HTMLNSLevelIndicatorCellElement.defineCustomElement();
  HTMLNSMagnificationGestureRecognizerElement.defineCustomElement();
  HTMLNSMatrixElement.defineCustomElement();
  HTMLNSMediaLibraryBrowserControllerElement.defineCustomElement();
  HTMLNSMenuElement.defineCustomElement();
  HTMLNSMenuItemElement.defineCustomElement();
  HTMLNSMenuItemBadgeElement.defineCustomElement();
  HTMLNSMenuItemCellElement.defineCustomElement();
  HTMLNSMenuToolbarItemElement.defineCustomElement();
  HTMLNSMovieElement.defineCustomElement();
  HTMLNSMutableFontCollectionElement.defineCustomElement();
  HTMLNSMutableParagraphStyleElement.defineCustomElement();
  HTMLNSNibElement.defineCustomElement();
  HTMLNSObjectElement.defineCustomElement();
  HTMLNSObjectControllerElement.defineCustomElement();
  HTMLNSOpenGLContextElement.defineCustomElement();
  HTMLNSOpenGLPixelBufferElement.defineCustomElement();
  HTMLNSOpenGLPixelFormatElement.defineCustomElement();
  HTMLNSOpenGLViewElement.defineCustomElement();
  HTMLNSOpenPanelElement.defineCustomElement();
  HTMLNSOutlineViewElement.defineCustomElement();
  HTMLNSPageControllerElement.defineCustomElement();
  HTMLNSPageLayoutElement.defineCustomElement();
  HTMLNSPanelElement.defineCustomElement();
  HTMLNSPanGestureRecognizerElement.defineCustomElement();
  HTMLNSParagraphStyleElement.defineCustomElement();
  HTMLNSPasteboardElement.defineCustomElement();
  HTMLNSPasteboardItemElement.defineCustomElement();
  HTMLNSPathCellElement.defineCustomElement();
  HTMLNSPathComponentCellElement.defineCustomElement();
  HTMLNSPathControlElement.defineCustomElement();
  HTMLNSPathControlItemElement.defineCustomElement();
  HTMLNSPDFImageRepElement.defineCustomElement();
  HTMLNSPDFInfoElement.defineCustomElement();
  HTMLNSPDFPanelElement.defineCustomElement();
  HTMLNSPersistentDocumentElement.defineCustomElement();
  HTMLNSPickerTouchBarItemElement.defineCustomElement();
  HTMLNSPICTImageRepElement.defineCustomElement();
  HTMLNSPopoverElement.defineCustomElement();
  HTMLNSPopoverTouchBarItemElement.defineCustomElement();
  HTMLNSPopUpButtonElement.defineCustomElement();
  HTMLNSPopUpButtonCellElement.defineCustomElement();
  HTMLNSPredicateEditorElement.defineCustomElement();
  HTMLNSPredicateEditorRowTemplateElement.defineCustomElement();
  HTMLNSPressGestureRecognizerElement.defineCustomElement();
  HTMLNSPressureConfigurationElement.defineCustomElement();
  HTMLNSPreviewRepresentingActivityItemElement.defineCustomElement();
  HTMLNSPrinterElement.defineCustomElement();
  HTMLNSPrintInfoElement.defineCustomElement();
  HTMLNSPrintOperationElement.defineCustomElement();
  HTMLNSPrintPanelElement.defineCustomElement();
  HTMLNSProgressIndicatorElement.defineCustomElement();
  HTMLNSResponderElement.defineCustomElement();
  HTMLNSRotationGestureRecognizerElement.defineCustomElement();
  HTMLNSRuleEditorElement.defineCustomElement();
  HTMLNSRulerMarkerElement.defineCustomElement();
  HTMLNSRulerViewElement.defineCustomElement();
  HTMLNSRunningApplicationElement.defineCustomElement();
  HTMLNSSavePanelElement.defineCustomElement();
  HTMLNSScreenElement.defineCustomElement();
  HTMLNSScrollerElement.defineCustomElement();
  HTMLNSScrollViewElement.defineCustomElement();
  HTMLNSScrubberElement.defineCustomElement();
  HTMLNSScrubberArrangedViewElement.defineCustomElement();
  HTMLNSScrubberFlowLayoutElement.defineCustomElement();
  HTMLNSScrubberImageItemViewElement.defineCustomElement();
  HTMLNSScrubberItemViewElement.defineCustomElement();
  HTMLNSScrubberLayoutElement.defineCustomElement();
  HTMLNSScrubberLayoutAttributesElement.defineCustomElement();
  HTMLNSScrubberProportionalLayoutElement.defineCustomElement();
  HTMLNSScrubberSelectionStyleElement.defineCustomElement();
  HTMLNSScrubberSelectionViewElement.defineCustomElement();
  HTMLNSScrubberTextItemViewElement.defineCustomElement();
  HTMLNSSearchFieldElement.defineCustomElement();
  HTMLNSSearchFieldCellElement.defineCustomElement();
  HTMLNSSearchToolbarItemElement.defineCustomElement();
  HTMLNSSecureTextFieldElement.defineCustomElement();
  HTMLNSSecureTextFieldCellElement.defineCustomElement();
  HTMLNSSegmentedCellElement.defineCustomElement();
  HTMLNSSegmentedControlElement.defineCustomElement();
  HTMLNSShadowElement.defineCustomElement();
  HTMLNSSharingServiceElement.defineCustomElement();
  HTMLNSSharingServicePickerElement.defineCustomElement();
  HTMLNSSharingServicePickerToolbarItemElement.defineCustomElement();
  HTMLNSSharingServicePickerTouchBarItemElement.defineCustomElement();
  HTMLNSSliderElement.defineCustomElement();
  HTMLNSSliderAccessoryElement.defineCustomElement();
  HTMLNSSliderAccessoryBehaviorElement.defineCustomElement();
  HTMLNSSliderCellElement.defineCustomElement();
  HTMLNSSliderTouchBarItemElement.defineCustomElement();
  HTMLNSSoundElement.defineCustomElement();
  HTMLNSSpeechRecognizerElement.defineCustomElement();
  HTMLNSSpeechSynthesizerElement.defineCustomElement();
  HTMLNSSpellCheckerElement.defineCustomElement();
  HTMLNSSplitViewElement.defineCustomElement();
  HTMLNSSplitViewControllerElement.defineCustomElement();
  HTMLNSSplitViewItemElement.defineCustomElement();
  HTMLNSStackViewElement.defineCustomElement();
  HTMLNSStatusBarElement.defineCustomElement();
  HTMLNSStatusBarButtonElement.defineCustomElement();
  HTMLNSStatusItemElement.defineCustomElement();
  HTMLNSStepperElement.defineCustomElement();
  HTMLNSStepperCellElement.defineCustomElement();
  HTMLNSStepperTouchBarItemElement.defineCustomElement();
  HTMLNSStoryboardElement.defineCustomElement();
  HTMLNSStoryboardSegueElement.defineCustomElement();
  HTMLNSStringDrawingContextElement.defineCustomElement();
  HTMLNSSwitchElement.defineCustomElement();
  HTMLNSTableCellViewElement.defineCustomElement();
  HTMLNSTableColumnElement.defineCustomElement();
  HTMLNSTableHeaderCellElement.defineCustomElement();
  HTMLNSTableHeaderViewElement.defineCustomElement();
  HTMLNSTableRowViewElement.defineCustomElement();
  HTMLNSTableViewElement.defineCustomElement();
  HTMLNSTableViewDiffableDataSourceElement.defineCustomElement();
  HTMLNSTableViewRowActionElement.defineCustomElement();
  HTMLNSTabViewElement.defineCustomElement();
  HTMLNSTabViewControllerElement.defineCustomElement();
  HTMLNSTabViewItemElement.defineCustomElement();
  HTMLNSTextElement.defineCustomElement();
  HTMLNSTextAlternativesElement.defineCustomElement();
  HTMLNSTextAttachmentElement.defineCustomElement();
  HTMLNSTextAttachmentCellElement.defineCustomElement();
  HTMLNSTextAttachmentViewProviderElement.defineCustomElement();
  HTMLNSTextBlockElement.defineCustomElement();
  HTMLNSTextCheckingControllerElement.defineCustomElement();
  HTMLNSTextContainerElement.defineCustomElement();
  HTMLNSTextContentManagerElement.defineCustomElement();
  HTMLNSTextContentStorageElement.defineCustomElement();
  HTMLNSTextElementElement.defineCustomElement();
  HTMLNSTextFieldElement.defineCustomElement();
  HTMLNSTextFieldCellElement.defineCustomElement();
  HTMLNSTextFinderElement.defineCustomElement();
  HTMLNSTextInputContextElement.defineCustomElement();
  HTMLNSTextInsertionIndicatorElement.defineCustomElement();
  HTMLNSTextLayoutFragmentElement.defineCustomElement();
  HTMLNSTextLayoutManagerElement.defineCustomElement();
  HTMLNSTextLineFragmentElement.defineCustomElement();
  HTMLNSTextListElement.defineCustomElement();
  HTMLNSTextListElementElement.defineCustomElement();
  HTMLNSTextParagraphElement.defineCustomElement();
  HTMLNSTextRangeElement.defineCustomElement();
  HTMLNSTextSelectionElement.defineCustomElement();
  HTMLNSTextSelectionNavigationElement.defineCustomElement();
  HTMLNSTextTabElement.defineCustomElement();
  HTMLNSTextTableElement.defineCustomElement();
  HTMLNSTextTableBlockElement.defineCustomElement();
  HTMLNSTextViewElement.defineCustomElement();
  HTMLNSTextViewportLayoutControllerElement.defineCustomElement();
  HTMLNSTintConfigurationElement.defineCustomElement();
  HTMLNSTitlebarAccessoryViewControllerElement.defineCustomElement();
  HTMLNSTokenFieldElement.defineCustomElement();
  HTMLNSTokenFieldCellElement.defineCustomElement();
  HTMLNSToolbarElement.defineCustomElement();
  HTMLNSToolbarItemElement.defineCustomElement();
  HTMLNSToolbarItemGroupElement.defineCustomElement();
  HTMLNSTouchElement.defineCustomElement();
  HTMLNSTouchBarElement.defineCustomElement();
  HTMLNSTouchBarItemElement.defineCustomElement();
  HTMLNSTrackingAreaElement.defineCustomElement();
  HTMLNSTrackingSeparatorToolbarItemElement.defineCustomElement();
  HTMLNSTreeControllerElement.defineCustomElement();
  HTMLNSTreeNodeElement.defineCustomElement();
  HTMLNSTypesetterElement.defineCustomElement();
  HTMLNSUserDefaultsControllerElement.defineCustomElement();
  HTMLNSUserInterfaceCompressionOptionsElement.defineCustomElement();
  HTMLNSViewElement.defineCustomElement();
  HTMLNSViewAnimationElement.defineCustomElement();
  HTMLNSViewControllerElement.defineCustomElement();
  HTMLNSVisualEffectViewElement.defineCustomElement();
  HTMLNSWindowElement.defineCustomElement();
  HTMLNSWindowControllerElement.defineCustomElement();
  HTMLNSWindowTabElement.defineCustomElement();
  HTMLNSWindowTabGroupElement.defineCustomElement();
  HTMLNSWorkspaceElement.defineCustomElement();
  HTMLNSWorkspaceAuthorizationElement.defineCustomElement();
  HTMLNSWorkspaceOpenConfigurationElement.defineCustomElement();
}
