export async function registerAllElements() {
  const {
    HTMLNSCollectionLayoutAnchorElement,
    HTMLNSCollectionLayoutBoundarySupplementaryItemElement,
    HTMLNSCollectionLayoutDecorationItemElement,
    HTMLNSCollectionLayoutDimensionElement,
    HTMLNSCollectionLayoutEdgeSpacingElement,
    HTMLNSCollectionLayoutGroupElement,
    HTMLNSCollectionLayoutGroupCustomItemElement,
    HTMLNSCollectionLayoutItemElement,
    HTMLNSCollectionLayoutSectionElement,
    HTMLNSCollectionLayoutSizeElement,
    HTMLNSCollectionLayoutSpacingElement,
    HTMLNSCollectionLayoutSupplementaryItemElement,
    HTMLNSDataAssetElement,
    HTMLNSDiffableDataSourceSectionSnapshotElement,
    HTMLNSDiffableDataSourceSectionTransactionElement,
    HTMLNSDiffableDataSourceSnapshotElement,
    HTMLNSDiffableDataSourceTransactionElement,
    HTMLNSLayoutAnchorElement,
    HTMLNSLayoutConstraintElement,
    HTMLNSLayoutDimensionElement,
    HTMLNSLayoutManagerElement,
    HTMLNSLayoutXAxisAnchorElement,
    HTMLNSLayoutYAxisAnchorElement,
    HTMLNSMutableParagraphStyleElement,
    HTMLNSObjectElement,
    HTMLNSParagraphStyleElement,
    HTMLNSShadowElement,
    HTMLNSStringDrawingContextElement,
    HTMLNSTextAttachmentElement,
    HTMLNSTextAttachmentViewProviderElement,
    HTMLNSTextContainerElement,
    HTMLNSTextContentManagerElement,
    HTMLNSTextContentStorageElement,
    HTMLNSTextElementElement,
    HTMLNSTextLayoutFragmentElement,
    HTMLNSTextLayoutManagerElement,
    HTMLNSTextLineFragmentElement,
    HTMLNSTextListElement,
    HTMLNSTextListElementElement,
    HTMLNSTextParagraphElement,
    HTMLNSTextRangeElement,
    HTMLNSTextSelectionElement,
    HTMLNSTextSelectionNavigationElement,
    HTMLNSTextTabElement,
    HTMLNSTextViewportLayoutControllerElement,
    HTMLUIAccelerationElement,
    HTMLUIAccelerometerElement,
    HTMLUIAccessibilityCustomActionElement,
    HTMLUIAccessibilityCustomRotorElement,
    HTMLUIAccessibilityCustomRotorItemResultElement,
    HTMLUIAccessibilityCustomRotorSearchPredicateElement,
    HTMLUIAccessibilityElementElement,
    HTMLUIAccessibilityLocationDescriptorElement,
    HTMLUIActionElement,
    HTMLUIActionSheetElement,
    HTMLUIActivityElement,
    HTMLUIActivityIndicatorViewElement,
    HTMLUIActivityItemsConfigurationElement,
    HTMLUIActivityViewControllerElement,
    HTMLUIAlertActionElement,
    HTMLUIAlertControllerElement,
    HTMLUIAlertViewElement,
    HTMLUIApplicationElement,
    HTMLUIApplicationShortcutIconElement,
    HTMLUIApplicationShortcutItemElement,
    HTMLUIAttachmentBehaviorElement,
    HTMLUIBackgroundConfigurationElement,
    HTMLUIBandSelectionInteractionElement,
    HTMLUIBarAppearanceElement,
    HTMLUIBarButtonItemElement,
    HTMLUIBarButtonItemAppearanceElement,
    HTMLUIBarButtonItemGroupElement,
    HTMLUIBarButtonItemStateAppearanceElement,
    HTMLUIBarItemElement,
    HTMLUIBezierPathElement,
    HTMLUIBlurEffectElement,
    HTMLUIButtonElement,
    HTMLUIButtonConfigurationElement,
    HTMLUICalendarSelectionElement,
    HTMLUICalendarSelectionMultiDateElement,
    HTMLUICalendarSelectionSingleDateElement,
    HTMLUICalendarViewElement,
    HTMLUICalendarViewDecorationElement,
    HTMLUICellAccessoryElement,
    HTMLUICellAccessoryCheckmarkElement,
    HTMLUICellAccessoryCustomViewElement,
    HTMLUICellAccessoryDeleteElement,
    HTMLUICellAccessoryDetailElement,
    HTMLUICellAccessoryDisclosureIndicatorElement,
    HTMLUICellAccessoryInsertElement,
    HTMLUICellAccessoryLabelElement,
    HTMLUICellAccessoryMultiselectElement,
    HTMLUICellAccessoryOutlineDisclosureElement,
    HTMLUICellAccessoryPopUpMenuElement,
    HTMLUICellAccessoryReorderElement,
    HTMLUICellConfigurationStateElement,
    HTMLUICloudSharingControllerElement,
    HTMLUICollectionLayoutListConfigurationElement,
    HTMLUICollectionLayoutSectionOrthogonalScrollingPropertiesElement,
    HTMLUICollectionReusableViewElement,
    HTMLUICollectionViewElement,
    HTMLUICollectionViewCellElement,
    HTMLUICollectionViewCellRegistrationElement,
    HTMLUICollectionViewCompositionalLayoutElement,
    HTMLUICollectionViewCompositionalLayoutConfigurationElement,
    HTMLUICollectionViewControllerElement,
    HTMLUICollectionViewDiffableDataSourceElement,
    HTMLUICollectionViewDiffableDataSourceReorderingHandlersElement,
    HTMLUICollectionViewDiffableDataSourceSectionSnapshotHandlersElement,
    HTMLUICollectionViewDropPlaceholderElement,
    HTMLUICollectionViewDropProposalElement,
    HTMLUICollectionViewFlowLayoutElement,
    HTMLUICollectionViewFlowLayoutInvalidationContextElement,
    HTMLUICollectionViewFocusUpdateContextElement,
    HTMLUICollectionViewLayoutElement,
    HTMLUICollectionViewLayoutAttributesElement,
    HTMLUICollectionViewLayoutInvalidationContextElement,
    HTMLUICollectionViewListCellElement,
    HTMLUICollectionViewPlaceholderElement,
    HTMLUICollectionViewSupplementaryRegistrationElement,
    HTMLUICollectionViewTransitionLayoutElement,
    HTMLUICollectionViewUpdateItemElement,
    HTMLUICollisionBehaviorElement,
    HTMLUIColorElement,
    HTMLUIColorPickerViewControllerElement,
    HTMLUIColorWellElement,
    HTMLUICommandElement,
    HTMLUICommandAlternateElement,
    HTMLUIContentUnavailableButtonPropertiesElement,
    HTMLUIContentUnavailableConfigurationElement,
    HTMLUIContentUnavailableConfigurationStateElement,
    HTMLUIContentUnavailableImagePropertiesElement,
    HTMLUIContentUnavailableTextPropertiesElement,
    HTMLUIContentUnavailableViewElement,
    HTMLUIContextMenuConfigurationElement,
    HTMLUIContextMenuInteractionElement,
    HTMLUIContextualActionElement,
    HTMLUIControlElement,
    HTMLUICubicTimingParametersElement,
    HTMLUIDatePickerElement,
    HTMLUIDeferredMenuElementElement,
    HTMLUIDeviceElement,
    HTMLUIDictationPhraseElement,
    HTMLUIDocumentElement,
    HTMLUIDocumentBrowserActionElement,
    HTMLUIDocumentBrowserTransitionControllerElement,
    HTMLUIDocumentBrowserViewControllerElement,
    HTMLUIDocumentInteractionControllerElement,
    HTMLUIDocumentMenuViewControllerElement,
    HTMLUIDocumentPickerExtensionViewControllerElement,
    HTMLUIDocumentPickerViewControllerElement,
    HTMLUIDocumentPropertiesElement,
    HTMLUIDocumentViewControllerElement,
    HTMLUIDragInteractionElement,
    HTMLUIDragItemElement,
    HTMLUIDragPreviewElement,
    HTMLUIDragPreviewParametersElement,
    HTMLUIDragPreviewTargetElement,
    HTMLUIDropInteractionElement,
    HTMLUIDropProposalElement,
    HTMLUIDynamicAnimatorElement,
    HTMLUIDynamicBehaviorElement,
    HTMLUIDynamicItemBehaviorElement,
    HTMLUIDynamicItemGroupElement,
    HTMLUIEditMenuConfigurationElement,
    HTMLUIEditMenuInteractionElement,
    HTMLUIEventElement,
    HTMLUIEventAttributionElement,
    HTMLUIEventAttributionViewElement,
    HTMLUIFeedbackGeneratorElement,
    HTMLUIFieldBehaviorElement,
    HTMLUIFindInteractionElement,
    HTMLUIFindSessionElement,
    HTMLUIFocusAnimationCoordinatorElement,
    HTMLUIFocusDebuggerElement,
    HTMLUIFocusEffectElement,
    HTMLUIFocusGuideElement,
    HTMLUIFocusHaloEffectElement,
    HTMLUIFocusMovementHintElement,
    HTMLUIFocusSystemElement,
    HTMLUIFocusUpdateContextElement,
    HTMLUIFontElement,
    HTMLUIFontDescriptorElement,
    HTMLUIFontMetricsElement,
    HTMLUIFontPickerViewControllerElement,
    HTMLUIFontPickerViewControllerConfigurationElement,
    HTMLUIGestureRecognizerElement,
    HTMLUIGraphicsImageRendererElement,
    HTMLUIGraphicsImageRendererContextElement,
    HTMLUIGraphicsImageRendererFormatElement,
    HTMLUIGraphicsPDFRendererElement,
    HTMLUIGraphicsPDFRendererContextElement,
    HTMLUIGraphicsPDFRendererFormatElement,
    HTMLUIGraphicsRendererElement,
    HTMLUIGraphicsRendererContextElement,
    HTMLUIGraphicsRendererFormatElement,
    HTMLUIGravityBehaviorElement,
    HTMLUIHoverAutomaticEffectElement,
    HTMLUIHoverGestureRecognizerElement,
    HTMLUIHoverHighlightEffectElement,
    HTMLUIHoverLiftEffectElement,
    HTMLUIHoverStyleElement,
    HTMLUIImageElement,
    HTMLUIImageAssetElement,
    HTMLUIImageConfigurationElement,
    HTMLUIImagePickerControllerElement,
    HTMLUIImageReaderElement,
    HTMLUIImageReaderConfigurationElement,
    HTMLUIImageSymbolConfigurationElement,
    HTMLUIImageViewElement,
    HTMLUIImpactFeedbackGeneratorElement,
    HTMLUIIndirectScribbleInteractionElement,
    HTMLUIInputViewElement,
    HTMLUIInputViewControllerElement,
    HTMLUIInterpolatingMotionEffectElement,
    HTMLUIKeyElement,
    HTMLUIKeyboardLayoutGuideElement,
    HTMLUIKeyCommandElement,
    HTMLUILabelElement,
    HTMLUILargeContentViewerInteractionElement,
    HTMLUILayoutGuideElement,
    HTMLUILexiconElement,
    HTMLUILexiconEntryElement,
    HTMLUIListContentConfigurationElement,
    HTMLUIListContentImagePropertiesElement,
    HTMLUIListContentTextPropertiesElement,
    HTMLUIListContentViewElement,
    HTMLUIListSeparatorConfigurationElement,
    HTMLUILocalizedIndexedCollationElement,
    HTMLUILocalNotificationElement,
    HTMLUILongPressGestureRecognizerElement,
    HTMLUIManagedDocumentElement,
    HTMLUIMarkupTextPrintFormatterElement,
    HTMLUIMenuElement,
    HTMLUIMenuControllerElement,
    HTMLUIMenuElementElement,
    HTMLUIMenuItemElement,
    HTMLUIMenuSystemElement,
    HTMLUIMotionEffectElement,
    HTMLUIMotionEffectGroupElement,
    HTMLUIMutableApplicationShortcutItemElement,
    HTMLUIMutableUserNotificationActionElement,
    HTMLUIMutableUserNotificationCategoryElement,
    HTMLUINavigationBarElement,
    HTMLUINavigationBarAppearanceElement,
    HTMLUINavigationControllerElement,
    HTMLUINavigationItemElement,
    HTMLUINibElement,
    HTMLUINotificationFeedbackGeneratorElement,
    HTMLUIOpenURLContextElement,
    HTMLUIPageControlElement,
    HTMLUIPageControlProgressElement,
    HTMLUIPageControlTimerProgressElement,
    HTMLUIPageViewControllerElement,
    HTMLUIPanGestureRecognizerElement,
    HTMLUIPasteboardElement,
    HTMLUIPasteConfigurationElement,
    HTMLUIPasteControlElement,
    HTMLUIPasteControlConfigurationElement,
    HTMLUIPencilInteractionElement,
    HTMLUIPercentDrivenInteractiveTransitionElement,
    HTMLUIPickerViewElement,
    HTMLUIPinchGestureRecognizerElement,
    HTMLUIPointerAccessoryElement,
    HTMLUIPointerEffectElement,
    HTMLUIPointerHighlightEffectElement,
    HTMLUIPointerHoverEffectElement,
    HTMLUIPointerInteractionElement,
    HTMLUIPointerLiftEffectElement,
    HTMLUIPointerLockStateElement,
    HTMLUIPointerRegionElement,
    HTMLUIPointerRegionRequestElement,
    HTMLUIPointerShapeElement,
    HTMLUIPointerStyleElement,
    HTMLUIPopoverBackgroundViewElement,
    HTMLUIPopoverControllerElement,
    HTMLUIPopoverPresentationControllerElement,
    HTMLUIPresentationControllerElement,
    HTMLUIPressElement,
    HTMLUIPressesEventElement,
    HTMLUIPreviewActionElement,
    HTMLUIPreviewActionGroupElement,
    HTMLUIPreviewInteractionElement,
    HTMLUIPreviewParametersElement,
    HTMLUIPreviewTargetElement,
    HTMLUIPrinterElement,
    HTMLUIPrinterDestinationElement,
    HTMLUIPrinterPickerControllerElement,
    HTMLUIPrintFormatterElement,
    HTMLUIPrintInfoElement,
    HTMLUIPrintInteractionControllerElement,
    HTMLUIPrintPageRendererElement,
    HTMLUIPrintPaperElement,
    HTMLUIPrintServiceExtensionElement,
    HTMLUIProgressViewElement,
    HTMLUIPushBehaviorElement,
    HTMLUIReferenceLibraryViewControllerElement,
    HTMLUIRefreshControlElement,
    HTMLUIRegionElement,
    HTMLUIResolvedShapeElement,
    HTMLUIResponderElement,
    HTMLUIRotationGestureRecognizerElement,
    HTMLUISceneElement,
    HTMLUISceneActivationConditionsElement,
    HTMLUISceneActivationRequestOptionsElement,
    HTMLUISceneConfigurationElement,
    HTMLUISceneConnectionOptionsElement,
    HTMLUISceneDestructionRequestOptionsElement,
    HTMLUISceneOpenExternalURLOptionsElement,
    HTMLUISceneOpenURLOptionsElement,
    HTMLUISceneSessionElement,
    HTMLUISceneSessionActivationRequestElement,
    HTMLUISceneSizeRestrictionsElement,
    HTMLUISceneWindowingBehaviorsElement,
    HTMLUIScreenElement,
    HTMLUIScreenEdgePanGestureRecognizerElement,
    HTMLUIScreenModeElement,
    HTMLUIScreenshotServiceElement,
    HTMLUIScribbleInteractionElement,
    HTMLUIScrollViewElement,
    HTMLUISearchBarElement,
    HTMLUISearchContainerViewControllerElement,
    HTMLUISearchControllerElement,
    HTMLUISearchDisplayControllerElement,
    HTMLUISearchSuggestionItemElement,
    HTMLUISearchTextFieldElement,
    HTMLUISearchTokenElement,
    HTMLUISegmentedControlElement,
    HTMLUISelectionFeedbackGeneratorElement,
    HTMLUIShapeElement,
    HTMLUIShapeResolutionContextElement,
    HTMLUISheetPresentationControllerElement,
    HTMLUISheetPresentationControllerDetentElement,
    HTMLUISimpleTextPrintFormatterElement,
    HTMLUISliderElement,
    HTMLUISnapBehaviorElement,
    HTMLUISplitViewControllerElement,
    HTMLUISpringLoadedInteractionElement,
    HTMLUISpringTimingParametersElement,
    HTMLUIStackViewElement,
    HTMLUIStatusBarManagerElement,
    HTMLUIStepperElement,
    HTMLUIStoryboardElement,
    HTMLUIStoryboardPopoverSegueElement,
    HTMLUIStoryboardSegueElement,
    HTMLUIStoryboardUnwindSegueSourceElement,
    HTMLUISwipeActionsConfigurationElement,
    HTMLUISwipeGestureRecognizerElement,
    HTMLUISwitchElement,
    HTMLUISymbolEffectCompletionContextElement,
    HTMLUITabBarElement,
    HTMLUITabBarAppearanceElement,
    HTMLUITabBarControllerElement,
    HTMLUITabBarItemElement,
    HTMLUITabBarItemAppearanceElement,
    HTMLUITabBarItemStateAppearanceElement,
    HTMLUITableViewElement,
    HTMLUITableViewCellElement,
    HTMLUITableViewControllerElement,
    HTMLUITableViewDiffableDataSourceElement,
    HTMLUITableViewDropPlaceholderElement,
    HTMLUITableViewDropProposalElement,
    HTMLUITableViewFocusUpdateContextElement,
    HTMLUITableViewHeaderFooterViewElement,
    HTMLUITableViewPlaceholderElement,
    HTMLUITableViewRowActionElement,
    HTMLUITapGestureRecognizerElement,
    HTMLUITargetedDragPreviewElement,
    HTMLUITargetedPreviewElement,
    HTMLUITextCheckerElement,
    HTMLUITextDragPreviewRendererElement,
    HTMLUITextDropProposalElement,
    HTMLUITextFieldElement,
    HTMLUITextFormattingCoordinatorElement,
    HTMLUITextInputAssistantItemElement,
    HTMLUITextInputContextElement,
    HTMLUITextInputModeElement,
    HTMLUITextInputPasswordRulesElement,
    HTMLUITextInputStringTokenizerElement,
    HTMLUITextInteractionElement,
    HTMLUITextItemElement,
    HTMLUITextItemMenuConfigurationElement,
    HTMLUITextItemMenuPreviewElement,
    HTMLUITextLoupeSessionElement,
    HTMLUITextPlaceholderElement,
    HTMLUITextPositionElement,
    HTMLUITextRangeElement,
    HTMLUITextSearchingFindSessionElement,
    HTMLUITextSearchOptionsElement,
    HTMLUITextSelectionDisplayInteractionElement,
    HTMLUITextSelectionRectElement,
    HTMLUITextViewElement,
    HTMLUIToolbarElement,
    HTMLUIToolbarAppearanceElement,
    HTMLUIToolTipConfigurationElement,
    HTMLUIToolTipInteractionElement,
    HTMLUITouchElement,
    HTMLUITrackingLayoutGuideElement,
    HTMLUITraitAccessibilityContrastElement,
    HTMLUITraitActiveAppearanceElement,
    HTMLUITraitCollectionElement,
    HTMLUITraitDisplayGamutElement,
    HTMLUITraitDisplayScaleElement,
    HTMLUITraitForceTouchCapabilityElement,
    HTMLUITraitHorizontalSizeClassElement,
    HTMLUITraitImageDynamicRangeElement,
    HTMLUITraitLayoutDirectionElement,
    HTMLUITraitLegibilityWeightElement,
    HTMLUITraitPreferredContentSizeCategoryElement,
    HTMLUITraitSceneCaptureStateElement,
    HTMLUITraitToolbarItemPresentationSizeElement,
    HTMLUITraitTypesettingLanguageElement,
    HTMLUITraitUserInterfaceIdiomElement,
    HTMLUITraitUserInterfaceLevelElement,
    HTMLUITraitUserInterfaceStyleElement,
    HTMLUITraitVerticalSizeClassElement,
    HTMLUIUserNotificationActionElement,
    HTMLUIUserNotificationCategoryElement,
    HTMLUIUserNotificationSettingsElement,
    HTMLUIVibrancyEffectElement,
    HTMLUIVideoEditorControllerElement,
    HTMLUIViewElement,
    HTMLUIViewConfigurationStateElement,
    HTMLUIViewControllerElement,
    HTMLUIViewPrintFormatterElement,
    HTMLUIViewPropertyAnimatorElement,
    HTMLUIVisualEffectElement,
    HTMLUIVisualEffectViewElement,
    HTMLUIWebViewElement,
    HTMLUIWindowElement,
    HTMLUIWindowSceneElement,
    HTMLUIWindowSceneActivationActionElement,
    HTMLUIWindowSceneActivationConfigurationElement,
    HTMLUIWindowSceneActivationInteractionElement,
    HTMLUIWindowSceneActivationRequestOptionsElement,
    HTMLUIWindowSceneDestructionRequestOptionsElement,
    HTMLUIWindowSceneDragInteractionElement,
    HTMLUIWindowSceneGeometryElement,
    HTMLUIWindowSceneGeometryPreferencesElement,
    HTMLUIWindowSceneGeometryPreferencesIOSElement,
    HTMLUIWindowSceneGeometryPreferencesMacElement,
    HTMLUIWindowScenePlacementElement,
    HTMLUIWindowSceneProminentPlacementElement,
    HTMLUIWindowSceneStandardPlacementElement,
  } = await import('./generated-elements.js');

  HTMLNSCollectionLayoutAnchorElement.defineCustomElement();
  HTMLNSCollectionLayoutBoundarySupplementaryItemElement.defineCustomElement();
  HTMLNSCollectionLayoutDecorationItemElement.defineCustomElement();
  HTMLNSCollectionLayoutDimensionElement.defineCustomElement();
  HTMLNSCollectionLayoutEdgeSpacingElement.defineCustomElement();
  HTMLNSCollectionLayoutGroupElement.defineCustomElement();
  HTMLNSCollectionLayoutGroupCustomItemElement.defineCustomElement();
  HTMLNSCollectionLayoutItemElement.defineCustomElement();
  HTMLNSCollectionLayoutSectionElement.defineCustomElement();
  HTMLNSCollectionLayoutSizeElement.defineCustomElement();
  HTMLNSCollectionLayoutSpacingElement.defineCustomElement();
  HTMLNSCollectionLayoutSupplementaryItemElement.defineCustomElement();
  HTMLNSDataAssetElement.defineCustomElement();
  HTMLNSDiffableDataSourceSectionSnapshotElement.defineCustomElement();
  HTMLNSDiffableDataSourceSectionTransactionElement.defineCustomElement();
  HTMLNSDiffableDataSourceSnapshotElement.defineCustomElement();
  HTMLNSDiffableDataSourceTransactionElement.defineCustomElement();
  HTMLNSLayoutAnchorElement.defineCustomElement();
  HTMLNSLayoutConstraintElement.defineCustomElement();
  HTMLNSLayoutDimensionElement.defineCustomElement();
  HTMLNSLayoutManagerElement.defineCustomElement();
  HTMLNSLayoutXAxisAnchorElement.defineCustomElement();
  HTMLNSLayoutYAxisAnchorElement.defineCustomElement();
  HTMLNSMutableParagraphStyleElement.defineCustomElement();
  HTMLNSObjectElement.defineCustomElement();
  HTMLNSParagraphStyleElement.defineCustomElement();
  HTMLNSShadowElement.defineCustomElement();
  HTMLNSStringDrawingContextElement.defineCustomElement();
  HTMLNSTextAttachmentElement.defineCustomElement();
  HTMLNSTextAttachmentViewProviderElement.defineCustomElement();
  HTMLNSTextContainerElement.defineCustomElement();
  HTMLNSTextContentManagerElement.defineCustomElement();
  HTMLNSTextContentStorageElement.defineCustomElement();
  HTMLNSTextElementElement.defineCustomElement();
  HTMLNSTextLayoutFragmentElement.defineCustomElement();
  HTMLNSTextLayoutManagerElement.defineCustomElement();
  HTMLNSTextLineFragmentElement.defineCustomElement();
  HTMLNSTextListElement.defineCustomElement();
  HTMLNSTextListElementElement.defineCustomElement();
  HTMLNSTextParagraphElement.defineCustomElement();
  HTMLNSTextRangeElement.defineCustomElement();
  HTMLNSTextSelectionElement.defineCustomElement();
  HTMLNSTextSelectionNavigationElement.defineCustomElement();
  HTMLNSTextTabElement.defineCustomElement();
  HTMLNSTextViewportLayoutControllerElement.defineCustomElement();
  HTMLUIAccelerationElement.defineCustomElement();
  HTMLUIAccelerometerElement.defineCustomElement();
  HTMLUIAccessibilityCustomActionElement.defineCustomElement();
  HTMLUIAccessibilityCustomRotorElement.defineCustomElement();
  HTMLUIAccessibilityCustomRotorItemResultElement.defineCustomElement();
  HTMLUIAccessibilityCustomRotorSearchPredicateElement.defineCustomElement();
  HTMLUIAccessibilityElementElement.defineCustomElement();
  HTMLUIAccessibilityLocationDescriptorElement.defineCustomElement();
  HTMLUIActionElement.defineCustomElement();
  HTMLUIActionSheetElement.defineCustomElement();
  HTMLUIActivityElement.defineCustomElement();
  HTMLUIActivityIndicatorViewElement.defineCustomElement();
  HTMLUIActivityItemsConfigurationElement.defineCustomElement();
  HTMLUIActivityViewControllerElement.defineCustomElement();
  HTMLUIAlertActionElement.defineCustomElement();
  HTMLUIAlertControllerElement.defineCustomElement();
  HTMLUIAlertViewElement.defineCustomElement();
  HTMLUIApplicationElement.defineCustomElement();
  HTMLUIApplicationShortcutIconElement.defineCustomElement();
  HTMLUIApplicationShortcutItemElement.defineCustomElement();
  HTMLUIAttachmentBehaviorElement.defineCustomElement();
  HTMLUIBackgroundConfigurationElement.defineCustomElement();
  HTMLUIBandSelectionInteractionElement.defineCustomElement();
  HTMLUIBarAppearanceElement.defineCustomElement();
  HTMLUIBarButtonItemElement.defineCustomElement();
  HTMLUIBarButtonItemAppearanceElement.defineCustomElement();
  HTMLUIBarButtonItemGroupElement.defineCustomElement();
  HTMLUIBarButtonItemStateAppearanceElement.defineCustomElement();
  HTMLUIBarItemElement.defineCustomElement();
  HTMLUIBezierPathElement.defineCustomElement();
  HTMLUIBlurEffectElement.defineCustomElement();
  HTMLUIButtonElement.defineCustomElement();
  HTMLUIButtonConfigurationElement.defineCustomElement();
  HTMLUICalendarSelectionElement.defineCustomElement();
  HTMLUICalendarSelectionMultiDateElement.defineCustomElement();
  HTMLUICalendarSelectionSingleDateElement.defineCustomElement();
  HTMLUICalendarViewElement.defineCustomElement();
  HTMLUICalendarViewDecorationElement.defineCustomElement();
  HTMLUICellAccessoryElement.defineCustomElement();
  HTMLUICellAccessoryCheckmarkElement.defineCustomElement();
  HTMLUICellAccessoryCustomViewElement.defineCustomElement();
  HTMLUICellAccessoryDeleteElement.defineCustomElement();
  HTMLUICellAccessoryDetailElement.defineCustomElement();
  HTMLUICellAccessoryDisclosureIndicatorElement.defineCustomElement();
  HTMLUICellAccessoryInsertElement.defineCustomElement();
  HTMLUICellAccessoryLabelElement.defineCustomElement();
  HTMLUICellAccessoryMultiselectElement.defineCustomElement();
  HTMLUICellAccessoryOutlineDisclosureElement.defineCustomElement();
  HTMLUICellAccessoryPopUpMenuElement.defineCustomElement();
  HTMLUICellAccessoryReorderElement.defineCustomElement();
  HTMLUICellConfigurationStateElement.defineCustomElement();
  HTMLUICloudSharingControllerElement.defineCustomElement();
  HTMLUICollectionLayoutListConfigurationElement.defineCustomElement();
  HTMLUICollectionLayoutSectionOrthogonalScrollingPropertiesElement.defineCustomElement();
  HTMLUICollectionReusableViewElement.defineCustomElement();
  HTMLUICollectionViewElement.defineCustomElement();
  HTMLUICollectionViewCellElement.defineCustomElement();
  HTMLUICollectionViewCellRegistrationElement.defineCustomElement();
  HTMLUICollectionViewCompositionalLayoutElement.defineCustomElement();
  HTMLUICollectionViewCompositionalLayoutConfigurationElement.defineCustomElement();
  HTMLUICollectionViewControllerElement.defineCustomElement();
  HTMLUICollectionViewDiffableDataSourceElement.defineCustomElement();
  HTMLUICollectionViewDiffableDataSourceReorderingHandlersElement.defineCustomElement();
  HTMLUICollectionViewDiffableDataSourceSectionSnapshotHandlersElement.defineCustomElement();
  HTMLUICollectionViewDropPlaceholderElement.defineCustomElement();
  HTMLUICollectionViewDropProposalElement.defineCustomElement();
  HTMLUICollectionViewFlowLayoutElement.defineCustomElement();
  HTMLUICollectionViewFlowLayoutInvalidationContextElement.defineCustomElement();
  HTMLUICollectionViewFocusUpdateContextElement.defineCustomElement();
  HTMLUICollectionViewLayoutElement.defineCustomElement();
  HTMLUICollectionViewLayoutAttributesElement.defineCustomElement();
  HTMLUICollectionViewLayoutInvalidationContextElement.defineCustomElement();
  HTMLUICollectionViewListCellElement.defineCustomElement();
  HTMLUICollectionViewPlaceholderElement.defineCustomElement();
  HTMLUICollectionViewSupplementaryRegistrationElement.defineCustomElement();
  HTMLUICollectionViewTransitionLayoutElement.defineCustomElement();
  HTMLUICollectionViewUpdateItemElement.defineCustomElement();
  HTMLUICollisionBehaviorElement.defineCustomElement();
  HTMLUIColorElement.defineCustomElement();
  HTMLUIColorPickerViewControllerElement.defineCustomElement();
  HTMLUIColorWellElement.defineCustomElement();
  HTMLUICommandElement.defineCustomElement();
  HTMLUICommandAlternateElement.defineCustomElement();
  HTMLUIContentUnavailableButtonPropertiesElement.defineCustomElement();
  HTMLUIContentUnavailableConfigurationElement.defineCustomElement();
  HTMLUIContentUnavailableConfigurationStateElement.defineCustomElement();
  HTMLUIContentUnavailableImagePropertiesElement.defineCustomElement();
  HTMLUIContentUnavailableTextPropertiesElement.defineCustomElement();
  HTMLUIContentUnavailableViewElement.defineCustomElement();
  HTMLUIContextMenuConfigurationElement.defineCustomElement();
  HTMLUIContextMenuInteractionElement.defineCustomElement();
  HTMLUIContextualActionElement.defineCustomElement();
  HTMLUIControlElement.defineCustomElement();
  HTMLUICubicTimingParametersElement.defineCustomElement();
  HTMLUIDatePickerElement.defineCustomElement();
  HTMLUIDeferredMenuElementElement.defineCustomElement();
  HTMLUIDeviceElement.defineCustomElement();
  HTMLUIDictationPhraseElement.defineCustomElement();
  HTMLUIDocumentElement.defineCustomElement();
  HTMLUIDocumentBrowserActionElement.defineCustomElement();
  HTMLUIDocumentBrowserTransitionControllerElement.defineCustomElement();
  HTMLUIDocumentBrowserViewControllerElement.defineCustomElement();
  HTMLUIDocumentInteractionControllerElement.defineCustomElement();
  HTMLUIDocumentMenuViewControllerElement.defineCustomElement();
  HTMLUIDocumentPickerExtensionViewControllerElement.defineCustomElement();
  HTMLUIDocumentPickerViewControllerElement.defineCustomElement();
  HTMLUIDocumentPropertiesElement.defineCustomElement();
  HTMLUIDocumentViewControllerElement.defineCustomElement();
  HTMLUIDragInteractionElement.defineCustomElement();
  HTMLUIDragItemElement.defineCustomElement();
  HTMLUIDragPreviewElement.defineCustomElement();
  HTMLUIDragPreviewParametersElement.defineCustomElement();
  HTMLUIDragPreviewTargetElement.defineCustomElement();
  HTMLUIDropInteractionElement.defineCustomElement();
  HTMLUIDropProposalElement.defineCustomElement();
  HTMLUIDynamicAnimatorElement.defineCustomElement();
  HTMLUIDynamicBehaviorElement.defineCustomElement();
  HTMLUIDynamicItemBehaviorElement.defineCustomElement();
  HTMLUIDynamicItemGroupElement.defineCustomElement();
  HTMLUIEditMenuConfigurationElement.defineCustomElement();
  HTMLUIEditMenuInteractionElement.defineCustomElement();
  HTMLUIEventElement.defineCustomElement();
  HTMLUIEventAttributionElement.defineCustomElement();
  HTMLUIEventAttributionViewElement.defineCustomElement();
  HTMLUIFeedbackGeneratorElement.defineCustomElement();
  HTMLUIFieldBehaviorElement.defineCustomElement();
  HTMLUIFindInteractionElement.defineCustomElement();
  HTMLUIFindSessionElement.defineCustomElement();
  HTMLUIFocusAnimationCoordinatorElement.defineCustomElement();
  HTMLUIFocusDebuggerElement.defineCustomElement();
  HTMLUIFocusEffectElement.defineCustomElement();
  HTMLUIFocusGuideElement.defineCustomElement();
  HTMLUIFocusHaloEffectElement.defineCustomElement();
  HTMLUIFocusMovementHintElement.defineCustomElement();
  HTMLUIFocusSystemElement.defineCustomElement();
  HTMLUIFocusUpdateContextElement.defineCustomElement();
  HTMLUIFontElement.defineCustomElement();
  HTMLUIFontDescriptorElement.defineCustomElement();
  HTMLUIFontMetricsElement.defineCustomElement();
  HTMLUIFontPickerViewControllerElement.defineCustomElement();
  HTMLUIFontPickerViewControllerConfigurationElement.defineCustomElement();
  HTMLUIGestureRecognizerElement.defineCustomElement();
  HTMLUIGraphicsImageRendererElement.defineCustomElement();
  HTMLUIGraphicsImageRendererContextElement.defineCustomElement();
  HTMLUIGraphicsImageRendererFormatElement.defineCustomElement();
  HTMLUIGraphicsPDFRendererElement.defineCustomElement();
  HTMLUIGraphicsPDFRendererContextElement.defineCustomElement();
  HTMLUIGraphicsPDFRendererFormatElement.defineCustomElement();
  HTMLUIGraphicsRendererElement.defineCustomElement();
  HTMLUIGraphicsRendererContextElement.defineCustomElement();
  HTMLUIGraphicsRendererFormatElement.defineCustomElement();
  HTMLUIGravityBehaviorElement.defineCustomElement();
  HTMLUIHoverAutomaticEffectElement.defineCustomElement();
  HTMLUIHoverGestureRecognizerElement.defineCustomElement();
  HTMLUIHoverHighlightEffectElement.defineCustomElement();
  HTMLUIHoverLiftEffectElement.defineCustomElement();
  HTMLUIHoverStyleElement.defineCustomElement();
  HTMLUIImageElement.defineCustomElement();
  HTMLUIImageAssetElement.defineCustomElement();
  HTMLUIImageConfigurationElement.defineCustomElement();
  HTMLUIImagePickerControllerElement.defineCustomElement();
  HTMLUIImageReaderElement.defineCustomElement();
  HTMLUIImageReaderConfigurationElement.defineCustomElement();
  HTMLUIImageSymbolConfigurationElement.defineCustomElement();
  HTMLUIImageViewElement.defineCustomElement();
  HTMLUIImpactFeedbackGeneratorElement.defineCustomElement();
  HTMLUIIndirectScribbleInteractionElement.defineCustomElement();
  HTMLUIInputViewElement.defineCustomElement();
  HTMLUIInputViewControllerElement.defineCustomElement();
  HTMLUIInterpolatingMotionEffectElement.defineCustomElement();
  HTMLUIKeyElement.defineCustomElement();
  HTMLUIKeyboardLayoutGuideElement.defineCustomElement();
  HTMLUIKeyCommandElement.defineCustomElement();
  HTMLUILabelElement.defineCustomElement();
  HTMLUILargeContentViewerInteractionElement.defineCustomElement();
  HTMLUILayoutGuideElement.defineCustomElement();
  HTMLUILexiconElement.defineCustomElement();
  HTMLUILexiconEntryElement.defineCustomElement();
  HTMLUIListContentConfigurationElement.defineCustomElement();
  HTMLUIListContentImagePropertiesElement.defineCustomElement();
  HTMLUIListContentTextPropertiesElement.defineCustomElement();
  HTMLUIListContentViewElement.defineCustomElement();
  HTMLUIListSeparatorConfigurationElement.defineCustomElement();
  HTMLUILocalizedIndexedCollationElement.defineCustomElement();
  HTMLUILocalNotificationElement.defineCustomElement();
  HTMLUILongPressGestureRecognizerElement.defineCustomElement();
  HTMLUIManagedDocumentElement.defineCustomElement();
  HTMLUIMarkupTextPrintFormatterElement.defineCustomElement();
  HTMLUIMenuElement.defineCustomElement();
  HTMLUIMenuControllerElement.defineCustomElement();
  HTMLUIMenuElementElement.defineCustomElement();
  HTMLUIMenuItemElement.defineCustomElement();
  HTMLUIMenuSystemElement.defineCustomElement();
  HTMLUIMotionEffectElement.defineCustomElement();
  HTMLUIMotionEffectGroupElement.defineCustomElement();
  HTMLUIMutableApplicationShortcutItemElement.defineCustomElement();
  HTMLUIMutableUserNotificationActionElement.defineCustomElement();
  HTMLUIMutableUserNotificationCategoryElement.defineCustomElement();
  HTMLUINavigationBarElement.defineCustomElement();
  HTMLUINavigationBarAppearanceElement.defineCustomElement();
  HTMLUINavigationControllerElement.defineCustomElement();
  HTMLUINavigationItemElement.defineCustomElement();
  HTMLUINibElement.defineCustomElement();
  HTMLUINotificationFeedbackGeneratorElement.defineCustomElement();
  HTMLUIOpenURLContextElement.defineCustomElement();
  HTMLUIPageControlElement.defineCustomElement();
  HTMLUIPageControlProgressElement.defineCustomElement();
  HTMLUIPageControlTimerProgressElement.defineCustomElement();
  HTMLUIPageViewControllerElement.defineCustomElement();
  HTMLUIPanGestureRecognizerElement.defineCustomElement();
  HTMLUIPasteboardElement.defineCustomElement();
  HTMLUIPasteConfigurationElement.defineCustomElement();
  HTMLUIPasteControlElement.defineCustomElement();
  HTMLUIPasteControlConfigurationElement.defineCustomElement();
  HTMLUIPencilInteractionElement.defineCustomElement();
  HTMLUIPercentDrivenInteractiveTransitionElement.defineCustomElement();
  HTMLUIPickerViewElement.defineCustomElement();
  HTMLUIPinchGestureRecognizerElement.defineCustomElement();
  HTMLUIPointerAccessoryElement.defineCustomElement();
  HTMLUIPointerEffectElement.defineCustomElement();
  HTMLUIPointerHighlightEffectElement.defineCustomElement();
  HTMLUIPointerHoverEffectElement.defineCustomElement();
  HTMLUIPointerInteractionElement.defineCustomElement();
  HTMLUIPointerLiftEffectElement.defineCustomElement();
  HTMLUIPointerLockStateElement.defineCustomElement();
  HTMLUIPointerRegionElement.defineCustomElement();
  HTMLUIPointerRegionRequestElement.defineCustomElement();
  HTMLUIPointerShapeElement.defineCustomElement();
  HTMLUIPointerStyleElement.defineCustomElement();
  HTMLUIPopoverBackgroundViewElement.defineCustomElement();
  HTMLUIPopoverControllerElement.defineCustomElement();
  HTMLUIPopoverPresentationControllerElement.defineCustomElement();
  HTMLUIPresentationControllerElement.defineCustomElement();
  HTMLUIPressElement.defineCustomElement();
  HTMLUIPressesEventElement.defineCustomElement();
  HTMLUIPreviewActionElement.defineCustomElement();
  HTMLUIPreviewActionGroupElement.defineCustomElement();
  HTMLUIPreviewInteractionElement.defineCustomElement();
  HTMLUIPreviewParametersElement.defineCustomElement();
  HTMLUIPreviewTargetElement.defineCustomElement();
  HTMLUIPrinterElement.defineCustomElement();
  HTMLUIPrinterDestinationElement.defineCustomElement();
  HTMLUIPrinterPickerControllerElement.defineCustomElement();
  HTMLUIPrintFormatterElement.defineCustomElement();
  HTMLUIPrintInfoElement.defineCustomElement();
  HTMLUIPrintInteractionControllerElement.defineCustomElement();
  HTMLUIPrintPageRendererElement.defineCustomElement();
  HTMLUIPrintPaperElement.defineCustomElement();
  HTMLUIPrintServiceExtensionElement.defineCustomElement();
  HTMLUIProgressViewElement.defineCustomElement();
  HTMLUIPushBehaviorElement.defineCustomElement();
  HTMLUIReferenceLibraryViewControllerElement.defineCustomElement();
  HTMLUIRefreshControlElement.defineCustomElement();
  HTMLUIRegionElement.defineCustomElement();
  HTMLUIResolvedShapeElement.defineCustomElement();
  HTMLUIResponderElement.defineCustomElement();
  HTMLUIRotationGestureRecognizerElement.defineCustomElement();
  HTMLUISceneElement.defineCustomElement();
  HTMLUISceneActivationConditionsElement.defineCustomElement();
  HTMLUISceneActivationRequestOptionsElement.defineCustomElement();
  HTMLUISceneConfigurationElement.defineCustomElement();
  HTMLUISceneConnectionOptionsElement.defineCustomElement();
  HTMLUISceneDestructionRequestOptionsElement.defineCustomElement();
  HTMLUISceneOpenExternalURLOptionsElement.defineCustomElement();
  HTMLUISceneOpenURLOptionsElement.defineCustomElement();
  HTMLUISceneSessionElement.defineCustomElement();
  HTMLUISceneSessionActivationRequestElement.defineCustomElement();
  HTMLUISceneSizeRestrictionsElement.defineCustomElement();
  HTMLUISceneWindowingBehaviorsElement.defineCustomElement();
  HTMLUIScreenElement.defineCustomElement();
  HTMLUIScreenEdgePanGestureRecognizerElement.defineCustomElement();
  HTMLUIScreenModeElement.defineCustomElement();
  HTMLUIScreenshotServiceElement.defineCustomElement();
  HTMLUIScribbleInteractionElement.defineCustomElement();
  HTMLUIScrollViewElement.defineCustomElement();
  HTMLUISearchBarElement.defineCustomElement();
  HTMLUISearchContainerViewControllerElement.defineCustomElement();
  HTMLUISearchControllerElement.defineCustomElement();
  HTMLUISearchDisplayControllerElement.defineCustomElement();
  HTMLUISearchSuggestionItemElement.defineCustomElement();
  HTMLUISearchTextFieldElement.defineCustomElement();
  HTMLUISearchTokenElement.defineCustomElement();
  HTMLUISegmentedControlElement.defineCustomElement();
  HTMLUISelectionFeedbackGeneratorElement.defineCustomElement();
  HTMLUIShapeElement.defineCustomElement();
  HTMLUIShapeResolutionContextElement.defineCustomElement();
  HTMLUISheetPresentationControllerElement.defineCustomElement();
  HTMLUISheetPresentationControllerDetentElement.defineCustomElement();
  HTMLUISimpleTextPrintFormatterElement.defineCustomElement();
  HTMLUISliderElement.defineCustomElement();
  HTMLUISnapBehaviorElement.defineCustomElement();
  HTMLUISplitViewControllerElement.defineCustomElement();
  HTMLUISpringLoadedInteractionElement.defineCustomElement();
  HTMLUISpringTimingParametersElement.defineCustomElement();
  HTMLUIStackViewElement.defineCustomElement();
  HTMLUIStatusBarManagerElement.defineCustomElement();
  HTMLUIStepperElement.defineCustomElement();
  HTMLUIStoryboardElement.defineCustomElement();
  HTMLUIStoryboardPopoverSegueElement.defineCustomElement();
  HTMLUIStoryboardSegueElement.defineCustomElement();
  HTMLUIStoryboardUnwindSegueSourceElement.defineCustomElement();
  HTMLUISwipeActionsConfigurationElement.defineCustomElement();
  HTMLUISwipeGestureRecognizerElement.defineCustomElement();
  HTMLUISwitchElement.defineCustomElement();
  HTMLUISymbolEffectCompletionContextElement.defineCustomElement();
  HTMLUITabBarElement.defineCustomElement();
  HTMLUITabBarAppearanceElement.defineCustomElement();
  HTMLUITabBarControllerElement.defineCustomElement();
  HTMLUITabBarItemElement.defineCustomElement();
  HTMLUITabBarItemAppearanceElement.defineCustomElement();
  HTMLUITabBarItemStateAppearanceElement.defineCustomElement();
  HTMLUITableViewElement.defineCustomElement();
  HTMLUITableViewCellElement.defineCustomElement();
  HTMLUITableViewControllerElement.defineCustomElement();
  HTMLUITableViewDiffableDataSourceElement.defineCustomElement();
  HTMLUITableViewDropPlaceholderElement.defineCustomElement();
  HTMLUITableViewDropProposalElement.defineCustomElement();
  HTMLUITableViewFocusUpdateContextElement.defineCustomElement();
  HTMLUITableViewHeaderFooterViewElement.defineCustomElement();
  HTMLUITableViewPlaceholderElement.defineCustomElement();
  HTMLUITableViewRowActionElement.defineCustomElement();
  HTMLUITapGestureRecognizerElement.defineCustomElement();
  HTMLUITargetedDragPreviewElement.defineCustomElement();
  HTMLUITargetedPreviewElement.defineCustomElement();
  HTMLUITextCheckerElement.defineCustomElement();
  HTMLUITextDragPreviewRendererElement.defineCustomElement();
  HTMLUITextDropProposalElement.defineCustomElement();
  HTMLUITextFieldElement.defineCustomElement();
  HTMLUITextFormattingCoordinatorElement.defineCustomElement();
  HTMLUITextInputAssistantItemElement.defineCustomElement();
  HTMLUITextInputContextElement.defineCustomElement();
  HTMLUITextInputModeElement.defineCustomElement();
  HTMLUITextInputPasswordRulesElement.defineCustomElement();
  HTMLUITextInputStringTokenizerElement.defineCustomElement();
  HTMLUITextInteractionElement.defineCustomElement();
  HTMLUITextItemElement.defineCustomElement();
  HTMLUITextItemMenuConfigurationElement.defineCustomElement();
  HTMLUITextItemMenuPreviewElement.defineCustomElement();
  HTMLUITextLoupeSessionElement.defineCustomElement();
  HTMLUITextPlaceholderElement.defineCustomElement();
  HTMLUITextPositionElement.defineCustomElement();
  HTMLUITextRangeElement.defineCustomElement();
  HTMLUITextSearchingFindSessionElement.defineCustomElement();
  HTMLUITextSearchOptionsElement.defineCustomElement();
  HTMLUITextSelectionDisplayInteractionElement.defineCustomElement();
  HTMLUITextSelectionRectElement.defineCustomElement();
  HTMLUITextViewElement.defineCustomElement();
  HTMLUIToolbarElement.defineCustomElement();
  HTMLUIToolbarAppearanceElement.defineCustomElement();
  HTMLUIToolTipConfigurationElement.defineCustomElement();
  HTMLUIToolTipInteractionElement.defineCustomElement();
  HTMLUITouchElement.defineCustomElement();
  HTMLUITrackingLayoutGuideElement.defineCustomElement();
  HTMLUITraitAccessibilityContrastElement.defineCustomElement();
  HTMLUITraitActiveAppearanceElement.defineCustomElement();
  HTMLUITraitCollectionElement.defineCustomElement();
  HTMLUITraitDisplayGamutElement.defineCustomElement();
  HTMLUITraitDisplayScaleElement.defineCustomElement();
  HTMLUITraitForceTouchCapabilityElement.defineCustomElement();
  HTMLUITraitHorizontalSizeClassElement.defineCustomElement();
  HTMLUITraitImageDynamicRangeElement.defineCustomElement();
  HTMLUITraitLayoutDirectionElement.defineCustomElement();
  HTMLUITraitLegibilityWeightElement.defineCustomElement();
  HTMLUITraitPreferredContentSizeCategoryElement.defineCustomElement();
  HTMLUITraitSceneCaptureStateElement.defineCustomElement();
  HTMLUITraitToolbarItemPresentationSizeElement.defineCustomElement();
  HTMLUITraitTypesettingLanguageElement.defineCustomElement();
  HTMLUITraitUserInterfaceIdiomElement.defineCustomElement();
  HTMLUITraitUserInterfaceLevelElement.defineCustomElement();
  HTMLUITraitUserInterfaceStyleElement.defineCustomElement();
  HTMLUITraitVerticalSizeClassElement.defineCustomElement();
  HTMLUIUserNotificationActionElement.defineCustomElement();
  HTMLUIUserNotificationCategoryElement.defineCustomElement();
  HTMLUIUserNotificationSettingsElement.defineCustomElement();
  HTMLUIVibrancyEffectElement.defineCustomElement();
  HTMLUIVideoEditorControllerElement.defineCustomElement();
  HTMLUIViewElement.defineCustomElement();
  HTMLUIViewConfigurationStateElement.defineCustomElement();
  HTMLUIViewControllerElement.defineCustomElement();
  HTMLUIViewPrintFormatterElement.defineCustomElement();
  HTMLUIViewPropertyAnimatorElement.defineCustomElement();
  HTMLUIVisualEffectElement.defineCustomElement();
  HTMLUIVisualEffectViewElement.defineCustomElement();
  HTMLUIWebViewElement.defineCustomElement();
  HTMLUIWindowElement.defineCustomElement();
  HTMLUIWindowSceneElement.defineCustomElement();
  HTMLUIWindowSceneActivationActionElement.defineCustomElement();
  HTMLUIWindowSceneActivationConfigurationElement.defineCustomElement();
  HTMLUIWindowSceneActivationInteractionElement.defineCustomElement();
  HTMLUIWindowSceneActivationRequestOptionsElement.defineCustomElement();
  HTMLUIWindowSceneDestructionRequestOptionsElement.defineCustomElement();
  HTMLUIWindowSceneDragInteractionElement.defineCustomElement();
  HTMLUIWindowSceneGeometryElement.defineCustomElement();
  HTMLUIWindowSceneGeometryPreferencesElement.defineCustomElement();
  HTMLUIWindowSceneGeometryPreferencesIOSElement.defineCustomElement();
  HTMLUIWindowSceneGeometryPreferencesMacElement.defineCustomElement();
  HTMLUIWindowScenePlacementElement.defineCustomElement();
  HTMLUIWindowSceneProminentPlacementElement.defineCustomElement();
  HTMLUIWindowSceneStandardPlacementElement.defineCustomElement();
}
